### ISSUE TITLE
Broken LICENSE link from homepage

### ISSUE THREAD

**Issue by dhanvsagar** [rishabkumar7/the-devops-guide#4]
Link to the MIT license from the homepage seems to be not working.

The current link is to https://github.com/rishabkumar7/the-devops-guide/blob/main/LICENSE and the actual license file is at https://github.com/rishabkumar7/the-devops-guide/blob/main/LICENSE.md

Shall I create a PR to fix the same..?

Thanks

**Comment by rishabkumar7** [comment]
hey @dhanvsagar , yes, feel free to open a PR

**Comment by rishabkumar7** [comment]
PR merged ✅
