### ISSUE TITLE
Feedback for “Version Control System”

### ISSUE THREAD

**Issue by freyandere** [rishabkumar7/the-devops-guide#6]
![image](https://user-images.githubusercontent.com/25580042/218312300-2f1e70ca-bc41-4036-bb7f-eb30ada9960e.png)
Button on the bottom, for the next chapter is not working, leading to an error 404.
![image](https://user-images.githubusercontent.com/25580042/218312332-55a9ab45-7072-4268-9c37-cda751041ba9.png)

**Comment by rishabkumar7** [comment]
Thanks for the issue, I have updated the markdown :)
