### ISSUE TITLE
fix: Add GitHub link

### ISSUE THREAD

**Issue by priyankarpal** [rishabkumar7/the-devops-guide#8]
### Please add the GitHub repository's link in the header.

![image](https://user-images.githubusercontent.com/88102392/227732999-9db21d37-47cb-4b70-a17f-b2ec5ad9f529.png)

**Comment by rishabkumar7** [comment]
Hey @priyankarpal thanks for opening the issue, I might have missed the notification, will get the link in the header.

**Comment by rishabkumar7** [comment]
@priyankarpal added the correct link to the header GitHub logo, it takes you to the repository now :)
