### ISSUE TITLE
fix: add the page link

### ISSUE THREAD

**Issue by priyankarpal** [rishabkumar7/the-devops-guide#9]
### in the last start here link not working. Please fix it. 

https://user-images.githubusercontent.com/88102392/227733156-89702f0c-77ef-4938-a95f-41d657ca36c1.mp4

**Comment by rishabkumar7** [comment]
Hey @priyankarpal thanks for opening the issue, I might have missed the notification, will get the link fixed

**Comment by rishabkumar7** [comment]
The link now point to the correct address, the DevOps page.
